editor: source

execute:
  cache: false
  freeze: false

project:
  type: website
  output-dir: docs
  render: [index.qmd]
  post-render: "R/_post-render.R"

title: "Exploring Complexity with Agent-Based Models"
author: "Daniel Vartanian"
keyword: >
  Complexity Science. Complex Systems. Agent-Based Modeling.
  Individual-Based Modeling. Emergent Behavior. Dynamic Systems.
  Conceptual Models. Empirical Models. Adaptive Systems. Self-Organization.
  Computational Modeling. System Dynamics. Micro-Macro Interactions.
  Generative Science. Simulations. NetLogo.
institute: "University of SÃ£o Paulo"
date: 2024-08-15
date-format: long

website:
  favicon: images/sustentarea-icon.svg
  repo-url: https://github.com/danielvartan/resiclima-pres-1/
  site-url: https://danielvartan.github.io/resiclima-pres-1/
  issue-url: https://github.com/danielvartan/resiclima-pres-1/issues/
  open-graph:
    image: images/og-image.png
    image-width: 2400
    image-height: 1600
    image-alt: Sustentarea Research and Extension Group
  repo-branch: main

format:
  revealjs:
    open-graph: true
    locale: en
    lang: en
    code-link: true
    code-fold: true
    link-external-newwindow: true
    tbl-cap-location: top
    callout-appearance: simple
    csl: csl/english-apa-author-date.csl
    preview-links: false
    controls: true
    controls-layout: bottom-right
    auto-stretch: true
    fig-align: center
    theme: [default, brand, scss/styles.scss]
    pdf-max-pages-per-slide: 1
    template-partials:
      - html/title-slide.html
    menu:
      titleSelector: [h1 h2]
      useTextContentForMissingTitles: false
      hideMissingTitles: false
    include-in-header:
      text: |
        <meta property="og:description" content="">
        <meta property="og:image" content="/resiclima-pres-1/images/og-image.png">
        <meta property="og:image:height" content="2400">
        <meta property="og:image:width" content="1600">

google-scholar: true
bibliography: references.bib
